
export type Source = 'DailyHunt' | 'Facebook' | 'X' | 'YouTube' | 'Google';

export type NewsArticle = {
  id: string;
  district: string;
  source: Source;
  headline: string;
  content: string;
  imageUrls: string[];
  timestamp: Date;
  url: string;
  embedUrl?: string;
};

export const karnatakaDistricts: string[] = [
  'Bagalkote',
  'Ballari',
  'Belagavi',
  'Bengaluru Rural',
  'Bengaluru Urban',
  'Bidar',
  'Chamarajanagara',
  'Chikkaballapura',
  'Chikkamagaluru',
  'Chitradurga',
  'Dakshina Kannada',
  'Davanagere',
  'Dharwad',
  'Gadag',
  'Hassan',
  'Haveri',
  'Kalaburagi',
  'Kodagu',
  'Kolara',
  'Koppala',
  'Mandya',
  'Mysuru',
  'Raichuru',
  'Ramanagara',
  'Shivamogga',
  'Tumakuru',
  'Udupi',
  'Uttara Kannada',
  'Vijayanagara',
  'Vijayapura',
  'Yadagiri',
];

export const mockNewsData: NewsArticle[] = [
    {
    id: '1',
    district: 'Bengaluru Urban',
    source: 'Google',
    headline: 'Heavy Rains Lash Bengaluru, Traffic Snarled in Many Areas',
    content: 'Bengaluru witnessed heavy rainfall on Tuesday evening, leading to waterlogging and traffic congestion in several parts of the city. Areas like Marathahalli, Silk Board, and Koramangala were heavily affected.',
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x401.png'],
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    url: 'https://news.google.com/articles/CBMiWWh0dHBzOi8vd3d3LnRoZWhpbmR1LmNvbS9uZXdzL2NpdGllcy9iZW5nYWx1cnUvaGVhdnktcmFpbnMtbGFzaC1iZW5nYWx1cnUtd2F0ZXJsb2dnaW5nLXRyYWZmaWMtc25hcmxzL2FydGljbGU2NjA5Mzc5OC5lY2XSAQA?hl=en-IN&gl=IN&ceid=IN%3Aen',
  },
  {
    id: '2',
    district: 'Mysuru',
    source: 'YouTube',
    headline: 'Mysuru Dasara Preparations in Full Swing',
    content: 'The preparations for the world-famous Mysuru Dasara are in their final stages. The Golden Howdah is being readied for the grand procession.',
    imageUrls: [],
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
    url: 'https://www.youtube.com/watch?v=cyi3q_T3tco',
    embedUrl: 'https://www.youtube.com/embed/cyi3q_T3tco',
  },
  {
    id: '3',
    district: 'Belagavi',
    source: 'X',
    headline: 'New Industrial Zone Announced in Belagavi',
    content: 'The state government has announced a new industrial zone in Belagavi to boost employment and manufacturing in the region.',
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/601x400.png'],
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
    url: 'https://x.com/search?q=Belagavi%20industrial%20zone&src=typed_query',
  },
  {
    id: '4',
    district: 'Dakshina Kannada',
    source: 'Facebook',
    headline: 'Traditional Kambala Event Draws Huge Crowds in Mangaluru',
    content: 'The annual Kambala buffalo race was held in a village near Mangaluru, attracting thousands of spectators from across the state.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
    url: 'https://www.facebook.com/search/top/?q=Kambala%20Mangaluru',
  },
  {
    id: '5',
    district: 'Shivamogga',
    source: 'DailyHunt',
    headline: 'Jog Falls Sees Increased Water Flow After Heavy Rains',
    content: 'The iconic Jog Falls is a sight to behold with increased water flow following heavy rainfall in the Western Ghats.',
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x402.png'],
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000), // 8 hours ago
    url: 'https://www.dailyhunt.in/news/india/english/jog+falls-topics',
  },
  {
    id: '6',
    district: 'Bengaluru Rural',
    source: 'YouTube',
    headline: 'Exploring Nandi Hills: A Perfect Weekend Getaway',
    content: 'A travel vlog showcasing the beauty of Nandi Hills, a popular tourist destination in Bengaluru Rural district.',
    imageUrls: [],
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
    url: 'https://www.youtube.com/watch?v=A4i2hB2tP6E',
    embedUrl: 'https://www.youtube.com/embed/A4i2hB2tP6E',
  },
  {
    id: '7',
    district: 'Bagalkote',
    source: 'Google',
    headline: 'UNESCO World Heritage Site Pattadakal Sees Rise in Tourist Footfall',
    content: 'The ancient temples of Pattadakal are attracting more tourists after recent promotional activities by the tourism department.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    url: 'https://news.google.com/articles/CBMiXGh0dHBzOi8vd3d3LnRoZWhpbmR1LmNvbS9uZXdzL25hdGlvbmFsL2thcm5hdGFrYS9wYXR0YWRha2FsLXRvLWdldC1hLW5ldy1sb29rLWFzLWEtdG91cmlzdC1odWIvYXJ0aWNsZTY1NTU4NjUxLmVjZQ?hl=en-IN&gl=IN&ceid=IN%3Aen',
  },
  {
    id: '8',
    district: 'Ballari',
    source: 'DailyHunt',
    headline: 'Steel Production in Ballari Hits Record High',
    content: 'The steel plants in Ballari have reported a record production this quarter, contributing significantly to the state\'s economy.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    url: 'https://www.dailyhunt.in/news/india/english/jsw+steel+ballari-topics',
  },
  {
    id: '9',
    district: 'Bidar',
    source: 'Facebook',
    headline: 'Bidriware Artisans Seek Government Support',
    content: 'The famous Bidriware artisans of Bidar are seeking government intervention to promote their craft and improve their livelihoods.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    url: 'https://www.facebook.com/search/top/?q=Bidriware%20artisans',
  },
  {
    id: '10',
    district: 'Chamarajanagara',
    source: 'YouTube',
    headline: 'Leopard Sighting Near BR Hills Causes Panic',
    content: 'A leopard was sighted near a village on the fringes of the Biligiriranga Hills Tiger Reserve, prompting forest officials to issue an alert.',
    imageUrls: [],
    timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000),
    url: 'https://www.youtube.com/watch?v=GlQpult3dJg',
    embedUrl: 'https://www.youtube.com/embed/GlQpult3dJg',
  },
  {
    id: '11',
    district: 'Chikkaballapura',
    source: 'X',
    headline: 'New Silk Cocoon Market Inaugurated in Chikkaballapura',
    content: 'A new state-of-the-art silk cocoon market was inaugurated today, aiming to provide better prices for sericulture farmers.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    url: 'https://x.com/search?q=chikkaballapur%20silk%20market&src=typed_query',
  },
  {
    id: '12',
    district: 'Chikkamagaluru',
    source: 'Google',
    headline: 'Coffee Plantation Owners Expect Bumper Crop This Year',
    content: 'With favorable weather conditions, coffee growers in Chikkamagaluru are expecting a high-yield bumper crop this season.',
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/602x400.png'],
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    url: 'https://news.google.com/articles/CBMiamh0dHBzOi8vd3d3LmJ1c2luZXNzbGluZS5jb20vbWFya2V0cy9jb21tb2RpdGllcy9jb2ZmZWUtZXhwb3J0ZXJzLWV5ZS1oaWdoZXIgcHJpY2VzLWFtaWQtY3JvcC1jb25jZXJucy9hcnRpY2xlNjU4MDM0NTUuZWPAA?hl=en-IN&gl=IN&ceid=IN%3Aen',
  },
  {
    id: '13',
    district: 'Chitradurga',
    source: 'DailyHunt',
    headline: 'Wind Energy Project Launched near Chitradurga Fort',
    content: 'A new wind energy project was launched to harness the high wind potential in the areas surrounding the historic Chitradurga Fort.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000),
    url: 'https://www.dailyhunt.in/news/india/kannada/chitradurga-topics',
  },
  {
    id: '14',
    district: 'Davanagere',
    source: 'Facebook',
    headline: 'Benne Dosa Festival a Huge Success in Davanagere',
    content: 'The annual Benne Dosa festival saw thousands of food lovers throng to Davanagere to taste the city\'s famous butter dosa.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    url: 'https://www.facebook.com/search/top/?q=Benne%20Dosa%20Festival%20Davanagere',
  },
  {
    id: '15',
    district: 'Dharwad',
    source: 'X',
    headline: 'Dharwad Pedha Gets Geographical Indication (GI) Tag',
    content: 'The famous Dharwad Pedha has been awarded the GI tag, recognizing its unique origin and quality.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
    url: 'https://x.com/search?q=dharwad%20pedha%20gi%20tag&src=typed_query',
  },
  {
    id: '16',
    district: 'Gadag',
    source: 'YouTube',
    headline: 'Exploring the Trikuteshwara Temple Complex in Gadag',
    content: 'A detailed walkthrough of the ancient and architecturally significant Trikuteshwara temple in Gadag.',
    imageUrls: [],
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    url: 'https://www.youtube.com/watch?v=kru0f_9Yk3I',
    embedUrl: 'https://www.youtube.com/embed/kru0f_9Yk3I'
  },
  {
    id: '17',
    district: 'Hassan',
    source: 'Google',
    headline: 'ISRO\'s Master Control Facility in Hassan Plays Key Role in Chandrayaan-3',
    content: 'The Master Control Facility in Hassan is crucial for monitoring and controlling the satellites of the Chandrayaan-3 mission.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    url: 'https://news.google.com/articles/CBMiemh0dHBzOi8vd3d3LnRoZWhpbmR1LmNvbS9uZXdzL25hdGlvbmFsL2thcm5hdGFrYS9pc3Jvcy1tY2YtaW4taGFzc2FuLXBsYXlzLWNydWNpYWwtcm9sZS1pbi1jaGFuZHJheWFhbi0zLW1pc3Npb24vYXJ0aWNsZTY3MTg5OTQ4LmVjZQ?hl=en-IN&gl=IN&ceid=IN%3Aen',
  },
  {
    id: '18',
    district: 'Haveri',
    source: 'DailyHunt',
    headline: 'Byadgi Chilli Prices Soar in Haveri Market',
    content: 'The price of the famous Byadgi chilli has seen a sharp increase in the Haveri market due to high demand and low supply.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 2.5 * 24 * 60 * 60 * 1000),
    url: 'https://www.dailyhunt.in/news/india/english/byadgi+chilli-topics',
  },
  {
    id: '19',
    district: 'Kalaburagi',
    source: 'Facebook',
    headline: 'Gulbarga Fort to be Developed as a Major Tourist Hub',
    content: 'The state government has announced a major project to restore and develop the historic Gulbarga Fort into a prime tourist destination.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    url: 'https://www.facebook.com/search/top/?q=Gulbarga%20Fort',
  },
  {
    id: '20',
    district: 'Kodagu',
    source: 'YouTube',
    headline: 'Monsoon Fury: Landslides reported in parts of Kodagu',
    content: 'Heavy monsoon rains have triggered several landslides in the hilly district of Kodagu, affecting transportation and daily life.',
    imageUrls: [],
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000),
    url: 'https://www.youtube.com/watch?v=Rq_B0i_9y-A',
    embedUrl: 'https://www.youtube.com/embed/Rq_B0i_9y-A'
  },
  {
    id: '21',
    district: 'Kolara',
    source: 'X',
    headline: 'Gold Mining to Resume in Kolar Gold Fields (KGF)?',
    content: 'Speculation is rife about the possible resumption of gold mining in the historic Kolar Gold Fields after a recent government survey.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    url: 'https://x.com/search?q=Kolar%20Gold%20Fields&src=typed_query',
  },
  {
    id: '22',
    district: 'Koppala',
    source: 'Google',
    headline: 'Anjanadri Hills, Believed to be Birthplace of Lord Hanuman, Sees Devotee Rush',
    content: 'A large number of devotees are visiting Anjanadri Hills in Koppala, believed to be the birthplace of Lord Hanuman, for special prayers.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 9 * 60 * 60 * 1000),
    url: 'https://news.google.com/articles/CBMiemh0dHBzOi8vd3d3LmRla2FubmV3cy5jb20vbmF0aW9uL2FuamFuYWRyaS1oaWxsLWJpcnRocGxhY2Utb2YtaGFudW1hbi13aWxsLWJlLWRldmVsb3BlZC1hdC1hLWNvc3Qtb2YtcnMxMjAtY3JvcmUtMTE3MTQ4OS5odG1s?hl=en-IN&gl=IN&ceid=IN%3Aen',
  },
  {
    id: '23',
    district: 'Mandya',
    source: 'DailyHunt',
    headline: 'Sugarcane Farmers in Mandya Protest for Better Prices',
    content: 'Farmers in Mandya are protesting, demanding a higher price for their sugarcane produce from the sugar factories in the region.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    url: 'https://www.dailyhunt.in/news/india/kannada/mandya-topics',
  },
  {
    id: '24',
    district: 'Raichuru',
    source: 'Facebook',
    headline: 'Raichur Thermal Power Station Increases Output to Meet Demand',
    content: 'The Raichur Thermal Power Station has ramped up its electricity production to meet the increasing power demand in the state.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    url: 'https://www.facebook.com/search/top/?q=Raichur%20Thermal%20Power%20Station',
  },
  {
    id: '25',
    district: 'Ramanagara',
    source: 'YouTube',
    headline: 'Rock Climbing and Rappelling activities in Ramanagara',
    content: 'Experience the thrill of rock climbing in Ramanagara, the place made famous by the movie "Sholay".',
    imageUrls: [],
    timestamp: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    url: 'https://www.youtube.com/watch?v=z9TOLp9pAUM',
    embedUrl: 'https://www.youtube.com/embed/z9TOLp9pAUM'
  },
  {
    id: '26',
    district: 'Tumakuru',
    source: 'X',
    headline: 'Asia\'s Largest Solar Park in Tumakuru Exceeds Generation Targets',
    content: 'The Pavagada Solar Park in Tumakuru district has exceeded its power generation targets for the year, setting a new benchmark.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 45 * 60 * 1000),
    url: 'https://x.com/search?q=Pavagada%20Solar%20Park&src=typed_query',
  },
  {
    id: '27',
    district: 'Udupi',
    source: 'Google',
    headline: 'Udupi Sri Krishna Matha Prepares for Paryaya Festival',
    content: 'The famous Udupi Sri Krishna Matha is gearing up for the grand Paryaya festival, a biennial event that marks the handover of temple management.',
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/600x403.png'],
    timestamp: new Date(Date.now() - 15 * 60 * 60 * 1000),
    url: 'https://news.google.com/articles/CBMiamh0dHBzOi8vd3d3LnRoZWhpbmR1LmNvbS9uZXdzL2NpdGllcy9tYW5nYWx1cnUvdWR1cGktZ2VhcnMtdXAtZm9yLXB1dHRpZ2UtbXVzaHQuanRpY2xlNjYxMDU3NjUuZWPAA?hl=en-IN&gl=IN&ceid=IN%3Aen',
  },
  {
    id: '28',
    district: 'Uttara Kannada',
    source: 'DailyHunt',
    headline: 'Karwar Naval Base to be Expanded Under Project Seabird',
    content: 'The Indian Navy is expanding its base in Karwar under the second phase of Project Seabird, which will make it one of the largest naval bases in Asia.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 3.5 * 24 * 60 * 60 * 1000),
    url: 'https://www.dailyhunt.in/news/india/english/project+seabird-topics',
  },
  {
    id: '29',
    district: 'Vijayanagara',
    source: 'Facebook',
    headline: 'Hampi Utsav Dates Announced, Artists from Across India to Participate',
    content: 'The dates for the annual Hampi Utsav have been announced. The cultural extravaganza will feature artists and performers from all over the country.',
    imageUrls: ['https://placehold.co/600x400.png', 'https://placehold.co/603x400.png'],
    timestamp: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    url: 'https://www.facebook.com/search/top?q=Hampi%20Utsav',
  },
  {
    id: '30',
    district: 'Vijayapura',
    source: 'YouTube',
    headline: 'A Tour of the Magnificent Gol Gumbaz in Vijayapura',
    content: 'A historical tour of the Gol Gumbaz, the mausoleum of king Mohammed Adil Shah, which has one of the biggest domes in the world.',
    imageUrls: [],
    timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    url: 'https://www.youtube.com/watch?v=Cj-sSLxAl9U',
    embedUrl: 'https://www.youtube.com/embed/Cj-sSLxAl9U'
  },
  {
    id: '31',
    district: 'Yadagiri',
    source: 'X',
    headline: 'New Cement Plant to be Set Up in Yadagiri District',
    content: 'A leading cement manufacturer has announced plans to set up a new plant in Yadagiri, promising development and jobs for the region.',
    imageUrls: ['https://placehold.co/600x400.png'],
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    url: 'https://x.com/search?q=Yadgir%20cement%20plant&src=typed_query',
  }
];
